server:
  servlet:
    context-path: /ecommerce

spring:
  #mysql&mybatis
  datasource:
    ecommerce:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.10.10.22:3306/local_product?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
    umino:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.10.10.22:3306/umino?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
  redis:
    cluster:
      nodes:
        - 10.10.10.28:7001
        - 10.10.10.28:7002
        - 10.10.10.28:7003
        - 10.10.10.28:7004
        - 10.10.10.28:7005
        - 10.10.10.28:7006
    timeout: 5000
  data:
    redis:
      repositories:
        enabled: false
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secretKey: C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w
logging:
  level:
    com.solin.springmvc.mapper: debug
