
spring:
  #mysql&mybatis
  datasource:
    ecommerce:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.10.10.22:3306/local_product?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
    umino:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.10.10.22:3306/umino?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pageHelper
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSq
