server:
  servlet:
    context-path: /ecommerce
  port: 8080

spring:
  #mysql&mybatis
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.10.10.22:3306/local_product?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
          username: root
          password: root
      primary: master
#      seata: true
#      seata-mode: at

  redis:
    cluster:
      nodes:
        - 10.10.10.28:7001
        - 10.10.10.28:7002
        - 10.10.10.28:7003
        - 10.10.10.28:7004
        - 10.10.10.28:7005
        - 10.10.10.28:7006
    timeout: 5000
  data:
    redis:
      repositories:
        enabled: false

jwt:
  secretKey: C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w

ftp:
  ip: 180.76.108.173
  user: root
  password: xiaomeng123!
  port: 22
  filePath: /ecommerce/
  parentFilePath: publicFileUpload
  domain: http://m.dian7.net
#  prvKeyFilePath: /Users/c/Desktop/140.82.46.209-NewYork/picUser/id_rsa
#  pubKeyFilePath: /Users/c/Desktop/140.82.46.209-NewYork/picUser/id_rsa.pub

logging:
  level:
    com.xm.commerce.system.mapper: debug


#seata:
#  enabled: true
#  application-id: applicationName
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: false   #一定要是false
#  service:
#    vgroup-mapping:
#      my_test_tx_group: default  #key与上面的tx-service-group的值对应
#    grouplist:
#      default: 39.108.158.138:8091 #seata-server地址仅file注册中心需要
#  config:
#    type: file
#  registry:
#    type: file